### ISSUE TITLE
Can't login! redirected but can't login to forum using social account.

### ISSUE THREAD

**Issue by muhghazaliakbar** [oneall/social-login-mybb#2]
Hi, i had a problem with social login. i just finished install the plugin and set all configuration, API, etc but the social login can't login. any help?

**Comment by SchlesserClaude** [comment]
Hello,

could you please tell me which version of myBB you are using?

Regards,

**Comment by muhghazaliakbar** [comment]
here sir :) MyBB 1.8.14 (1814)
